version: "3.3"

services:
  db:
    image: mysql:latest
    restart: always
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: "user_pwd"
      MYSQL_DATABASE: "reactlibrarydatabase"
      MYSQL_USER: "user_db"
      MYSQL_PASSWORD: "user_pwd"
    ports:
      - "33306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: